[theme]
base                     = "light"
primaryColor             = "#CC0000"
backgroundColor          = "#FEF6EC"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#1a1a2a"
font                     = "sans serif"

[server]
headless = true
port     = 8501

[browser]
gatherUsageStats = false
